// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/v1/admin.proto

package featureflags

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeatureAdminService_CreateFeature_FullMethodName = "/featureflags.v1.FeatureAdminService/CreateFeature"
	FeatureAdminService_UpdateFeature_FullMethodName = "/featureflags.v1.FeatureAdminService/UpdateFeature"
	FeatureAdminService_DeleteFeature_FullMethodName = "/featureflags.v1.FeatureAdminService/DeleteFeature"
	FeatureAdminService_ListFeatures_FullMethodName  = "/featureflags.v1.FeatureAdminService/ListFeatures"
	FeatureAdminService_GetFeature_FullMethodName    = "/featureflags.v1.FeatureAdminService/GetFeature"
)

// FeatureAdminServiceClient is the client API for FeatureAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeatureAdminServiceClient interface {
	CreateFeature(ctx context.Context, in *CreateFeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error)
	UpdateFeature(ctx context.Context, in *UpdateFeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error)
	DeleteFeature(ctx context.Context, in *DeleteFeatureRequest, opts ...grpc.CallOption) (*DeleteFeatureResponse, error)
	ListFeatures(ctx context.Context, in *ListFeaturesRequest, opts ...grpc.CallOption) (*ListFeaturesResponse, error)
	GetFeature(ctx context.Context, in *GetFeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error)
}

type featureAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureAdminServiceClient(cc grpc.ClientConnInterface) FeatureAdminServiceClient {
	return &featureAdminServiceClient{cc}
}

func (c *featureAdminServiceClient) CreateFeature(ctx context.Context, in *CreateFeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureResponse)
	err := c.cc.Invoke(ctx, FeatureAdminService_CreateFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureAdminServiceClient) UpdateFeature(ctx context.Context, in *UpdateFeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureResponse)
	err := c.cc.Invoke(ctx, FeatureAdminService_UpdateFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureAdminServiceClient) DeleteFeature(ctx context.Context, in *DeleteFeatureRequest, opts ...grpc.CallOption) (*DeleteFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFeatureResponse)
	err := c.cc.Invoke(ctx, FeatureAdminService_DeleteFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureAdminServiceClient) ListFeatures(ctx context.Context, in *ListFeaturesRequest, opts ...grpc.CallOption) (*ListFeaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeaturesResponse)
	err := c.cc.Invoke(ctx, FeatureAdminService_ListFeatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureAdminServiceClient) GetFeature(ctx context.Context, in *GetFeatureRequest, opts ...grpc.CallOption) (*FeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureResponse)
	err := c.cc.Invoke(ctx, FeatureAdminService_GetFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeatureAdminServiceServer is the server API for FeatureAdminService service.
// All implementations must embed UnimplementedFeatureAdminServiceServer
// for forward compatibility.
type FeatureAdminServiceServer interface {
	CreateFeature(context.Context, *CreateFeatureRequest) (*FeatureResponse, error)
	UpdateFeature(context.Context, *UpdateFeatureRequest) (*FeatureResponse, error)
	DeleteFeature(context.Context, *DeleteFeatureRequest) (*DeleteFeatureResponse, error)
	ListFeatures(context.Context, *ListFeaturesRequest) (*ListFeaturesResponse, error)
	GetFeature(context.Context, *GetFeatureRequest) (*FeatureResponse, error)
	mustEmbedUnimplementedFeatureAdminServiceServer()
}

// UnimplementedFeatureAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeatureAdminServiceServer struct{}

func (UnimplementedFeatureAdminServiceServer) CreateFeature(context.Context, *CreateFeatureRequest) (*FeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFeature not implemented")
}
func (UnimplementedFeatureAdminServiceServer) UpdateFeature(context.Context, *UpdateFeatureRequest) (*FeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFeature not implemented")
}
func (UnimplementedFeatureAdminServiceServer) DeleteFeature(context.Context, *DeleteFeatureRequest) (*DeleteFeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFeature not implemented")
}
func (UnimplementedFeatureAdminServiceServer) ListFeatures(context.Context, *ListFeaturesRequest) (*ListFeaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeatures not implemented")
}
func (UnimplementedFeatureAdminServiceServer) GetFeature(context.Context, *GetFeatureRequest) (*FeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeature not implemented")
}
func (UnimplementedFeatureAdminServiceServer) mustEmbedUnimplementedFeatureAdminServiceServer() {}
func (UnimplementedFeatureAdminServiceServer) testEmbeddedByValue()                             {}

// UnsafeFeatureAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureAdminServiceServer will
// result in compilation errors.
type UnsafeFeatureAdminServiceServer interface {
	mustEmbedUnimplementedFeatureAdminServiceServer()
}

func RegisterFeatureAdminServiceServer(s grpc.ServiceRegistrar, srv FeatureAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedFeatureAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeatureAdminService_ServiceDesc, srv)
}

func _FeatureAdminService_CreateFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureAdminServiceServer).CreateFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureAdminService_CreateFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureAdminServiceServer).CreateFeature(ctx, req.(*CreateFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureAdminService_UpdateFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureAdminServiceServer).UpdateFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureAdminService_UpdateFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureAdminServiceServer).UpdateFeature(ctx, req.(*UpdateFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureAdminService_DeleteFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureAdminServiceServer).DeleteFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureAdminService_DeleteFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureAdminServiceServer).DeleteFeature(ctx, req.(*DeleteFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureAdminService_ListFeatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureAdminServiceServer).ListFeatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureAdminService_ListFeatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureAdminServiceServer).ListFeatures(ctx, req.(*ListFeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureAdminService_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureAdminServiceServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureAdminService_GetFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureAdminServiceServer).GetFeature(ctx, req.(*GetFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeatureAdminService_ServiceDesc is the grpc.ServiceDesc for FeatureAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "featureflags.v1.FeatureAdminService",
	HandlerType: (*FeatureAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFeature",
			Handler:    _FeatureAdminService_CreateFeature_Handler,
		},
		{
			MethodName: "UpdateFeature",
			Handler:    _FeatureAdminService_UpdateFeature_Handler,
		},
		{
			MethodName: "DeleteFeature",
			Handler:    _FeatureAdminService_DeleteFeature_Handler,
		},
		{
			MethodName: "ListFeatures",
			Handler:    _FeatureAdminService_ListFeatures_Handler,
		},
		{
			MethodName: "GetFeature",
			Handler:    _FeatureAdminService_GetFeature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/admin.proto",
}
