// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/admin.proto

package featureflags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       *FeatureFlag           `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFeatureRequest) Reset() {
	*x = CreateFeatureRequest{}
	mi := &file_proto_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeatureRequest) ProtoMessage() {}

func (x *CreateFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeatureRequest.ProtoReflect.Descriptor instead.
func (*CreateFeatureRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFeatureRequest) GetFeature() *FeatureFlag {
	if x != nil {
		return x.Feature
	}
	return nil
}

type UpdateFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       *FeatureFlag           `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFeatureRequest) Reset() {
	*x = UpdateFeatureRequest{}
	mi := &file_proto_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFeatureRequest) ProtoMessage() {}

func (x *UpdateFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFeatureRequest.ProtoReflect.Descriptor instead.
func (*UpdateFeatureRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateFeatureRequest) GetFeature() *FeatureFlag {
	if x != nil {
		return x.Feature
	}
	return nil
}

type DeleteFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeatureRequest) Reset() {
	*x = DeleteFeatureRequest{}
	mi := &file_proto_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeatureRequest) ProtoMessage() {}

func (x *DeleteFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeatureRequest.ProtoReflect.Descriptor instead.
func (*DeleteFeatureRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteFeatureRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteFeatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFeatureResponse) Reset() {
	*x = DeleteFeatureResponse{}
	mi := &file_proto_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFeatureResponse) ProtoMessage() {}

func (x *DeleteFeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFeatureResponse.ProtoReflect.Descriptor instead.
func (*DeleteFeatureResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFeatureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeatureRequest) Reset() {
	*x = GetFeatureRequest{}
	mi := &file_proto_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureRequest) ProtoMessage() {}

func (x *GetFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureRequest.ProtoReflect.Descriptor instead.
func (*GetFeatureRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeatureRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturesRequest) Reset() {
	*x = ListFeaturesRequest{}
	mi := &file_proto_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturesRequest) ProtoMessage() {}

func (x *ListFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturesRequest.ProtoReflect.Descriptor instead.
func (*ListFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_admin_proto_rawDescGZIP(), []int{5}
}

type ListFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []*FeatureFlag         `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturesResponse) Reset() {
	*x = ListFeaturesResponse{}
	mi := &file_proto_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturesResponse) ProtoMessage() {}

func (x *ListFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturesResponse.ProtoReflect.Descriptor instead.
func (*ListFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListFeaturesResponse) GetFeatures() []*FeatureFlag {
	if x != nil {
		return x.Features
	}
	return nil
}

type FeatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       *FeatureFlag           `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureResponse) Reset() {
	*x = FeatureResponse{}
	mi := &file_proto_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureResponse) ProtoMessage() {}

func (x *FeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureResponse.ProtoReflect.Descriptor instead.
func (*FeatureResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *FeatureResponse) GetFeature() *FeatureFlag {
	if x != nil {
		return x.Feature
	}
	return nil
}

var File_proto_v1_admin_proto protoreflect.FileDescriptor

const file_proto_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/admin.proto\x12\x0ffeatureflags.v1\x1a\x15proto/v1/common.proto\"N\n" +
	"\x14CreateFeatureRequest\x126\n" +
	"\afeature\x18\x01 \x01(\v2\x1c.featureflags.v1.FeatureFlagR\afeature\"N\n" +
	"\x14UpdateFeatureRequest\x126\n" +
	"\afeature\x18\x01 \x01(\v2\x1c.featureflags.v1.FeatureFlagR\afeature\"(\n" +
	"\x14DeleteFeatureRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"1\n" +
	"\x15DeleteFeatureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x11GetFeatureRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x15\n" +
	"\x13ListFeaturesRequest\"P\n" +
	"\x14ListFeaturesResponse\x128\n" +
	"\bfeatures\x18\x01 \x03(\v2\x1c.featureflags.v1.FeatureFlagR\bfeatures\"I\n" +
	"\x0fFeatureResponse\x126\n" +
	"\afeature\x18\x01 \x01(\v2\x1c.featureflags.v1.FeatureFlagR\afeature2\xda\x03\n" +
	"\x13FeatureAdminService\x12X\n" +
	"\rCreateFeature\x12%.featureflags.v1.CreateFeatureRequest\x1a .featureflags.v1.FeatureResponse\x12X\n" +
	"\rUpdateFeature\x12%.featureflags.v1.UpdateFeatureRequest\x1a .featureflags.v1.FeatureResponse\x12^\n" +
	"\rDeleteFeature\x12%.featureflags.v1.DeleteFeatureRequest\x1a&.featureflags.v1.DeleteFeatureResponse\x12[\n" +
	"\fListFeatures\x12$.featureflags.v1.ListFeaturesRequest\x1a%.featureflags.v1.ListFeaturesResponse\x12R\n" +
	"\n" +
	"GetFeature\x12\".featureflags.v1.GetFeatureRequest\x1a .featureflags.v1.FeatureResponseB;Z9github.com/rafaelmaier/featureflags/proto/v1;featureflagsb\x06proto3"

var (
	file_proto_v1_admin_proto_rawDescOnce sync.Once
	file_proto_v1_admin_proto_rawDescData []byte
)

func file_proto_v1_admin_proto_rawDescGZIP() []byte {
	file_proto_v1_admin_proto_rawDescOnce.Do(func() {
		file_proto_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_admin_proto_rawDesc), len(file_proto_v1_admin_proto_rawDesc)))
	})
	return file_proto_v1_admin_proto_rawDescData
}

var file_proto_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_v1_admin_proto_goTypes = []any{
	(*CreateFeatureRequest)(nil),  // 0: featureflags.v1.CreateFeatureRequest
	(*UpdateFeatureRequest)(nil),  // 1: featureflags.v1.UpdateFeatureRequest
	(*DeleteFeatureRequest)(nil),  // 2: featureflags.v1.DeleteFeatureRequest
	(*DeleteFeatureResponse)(nil), // 3: featureflags.v1.DeleteFeatureResponse
	(*GetFeatureRequest)(nil),     // 4: featureflags.v1.GetFeatureRequest
	(*ListFeaturesRequest)(nil),   // 5: featureflags.v1.ListFeaturesRequest
	(*ListFeaturesResponse)(nil),  // 6: featureflags.v1.ListFeaturesResponse
	(*FeatureResponse)(nil),       // 7: featureflags.v1.FeatureResponse
	(*FeatureFlag)(nil),           // 8: featureflags.v1.FeatureFlag
}
var file_proto_v1_admin_proto_depIdxs = []int32{
	8, // 0: featureflags.v1.CreateFeatureRequest.feature:type_name -> featureflags.v1.FeatureFlag
	8, // 1: featureflags.v1.UpdateFeatureRequest.feature:type_name -> featureflags.v1.FeatureFlag
	8, // 2: featureflags.v1.ListFeaturesResponse.features:type_name -> featureflags.v1.FeatureFlag
	8, // 3: featureflags.v1.FeatureResponse.feature:type_name -> featureflags.v1.FeatureFlag
	0, // 4: featureflags.v1.FeatureAdminService.CreateFeature:input_type -> featureflags.v1.CreateFeatureRequest
	1, // 5: featureflags.v1.FeatureAdminService.UpdateFeature:input_type -> featureflags.v1.UpdateFeatureRequest
	2, // 6: featureflags.v1.FeatureAdminService.DeleteFeature:input_type -> featureflags.v1.DeleteFeatureRequest
	5, // 7: featureflags.v1.FeatureAdminService.ListFeatures:input_type -> featureflags.v1.ListFeaturesRequest
	4, // 8: featureflags.v1.FeatureAdminService.GetFeature:input_type -> featureflags.v1.GetFeatureRequest
	7, // 9: featureflags.v1.FeatureAdminService.CreateFeature:output_type -> featureflags.v1.FeatureResponse
	7, // 10: featureflags.v1.FeatureAdminService.UpdateFeature:output_type -> featureflags.v1.FeatureResponse
	3, // 11: featureflags.v1.FeatureAdminService.DeleteFeature:output_type -> featureflags.v1.DeleteFeatureResponse
	6, // 12: featureflags.v1.FeatureAdminService.ListFeatures:output_type -> featureflags.v1.ListFeaturesResponse
	7, // 13: featureflags.v1.FeatureAdminService.GetFeature:output_type -> featureflags.v1.FeatureResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_admin_proto_init() }
func file_proto_v1_admin_proto_init() {
	if File_proto_v1_admin_proto != nil {
		return
	}
	file_proto_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_admin_proto_rawDesc), len(file_proto_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_admin_proto_goTypes,
		DependencyIndexes: file_proto_v1_admin_proto_depIdxs,
		MessageInfos:      file_proto_v1_admin_proto_msgTypes,
	}.Build()
	File_proto_v1_admin_proto = out.File
	file_proto_v1_admin_proto_goTypes = nil
	file_proto_v1_admin_proto_depIdxs = nil
}
