// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/common.proto

package featureflags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rules         []*Rule                `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureFlag) Reset() {
	*x = FeatureFlag{}
	mi := &file_proto_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureFlag) ProtoMessage() {}

func (x *FeatureFlag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureFlag.ProtoReflect.Descriptor instead.
func (*FeatureFlag) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureFlag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FeatureFlag) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FeatureFlag) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *FeatureFlag) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Rule:
	//
	//	*Rule_Percentage
	//	*Rule_UserId
	Rule          isRule_Rule `protobuf_oneof:"Rule"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_proto_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetRule() isRule_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *Rule) GetPercentage() *PercentageRule {
	if x != nil {
		if x, ok := x.Rule.(*Rule_Percentage); ok {
			return x.Percentage
		}
	}
	return nil
}

func (x *Rule) GetUserId() *UserIDRule {
	if x != nil {
		if x, ok := x.Rule.(*Rule_UserId); ok {
			return x.UserId
		}
	}
	return nil
}

type isRule_Rule interface {
	isRule_Rule()
}

type Rule_Percentage struct {
	Percentage *PercentageRule `protobuf:"bytes,1,opt,name=percentage,proto3,oneof"`
}

type Rule_UserId struct {
	UserId *UserIDRule `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*Rule_Percentage) isRule_Rule() {}

func (*Rule_UserId) isRule_Rule() {}

type PercentageRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentage    int32                  `protobuf:"varint,1,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PercentageRule) Reset() {
	*x = PercentageRule{}
	mi := &file_proto_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PercentageRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PercentageRule) ProtoMessage() {}

func (x *PercentageRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PercentageRule.ProtoReflect.Descriptor instead.
func (*PercentageRule) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PercentageRule) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type UserIDRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRule) Reset() {
	*x = UserIDRule{}
	mi := &file_proto_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRule) ProtoMessage() {}

func (x *UserIDRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRule.ProtoReflect.Descriptor instead.
func (*UserIDRule) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *UserIDRule) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_proto_v1_common_proto protoreflect.FileDescriptor

const file_proto_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/common.proto\x12\x0ffeatureflags.v1\"\x80\x01\n" +
	"\vFeatureFlag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12+\n" +
	"\x05rules\x18\x03 \x03(\v2\x15.featureflags.v1.RuleR\x05rules\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"\x89\x01\n" +
	"\x04Rule\x12A\n" +
	"\n" +
	"percentage\x18\x01 \x01(\v2\x1f.featureflags.v1.PercentageRuleH\x00R\n" +
	"percentage\x126\n" +
	"\auser_id\x18\x02 \x01(\v2\x1b.featureflags.v1.UserIDRuleH\x00R\x06userIdB\x06\n" +
	"\x04Rule\"0\n" +
	"\x0ePercentageRule\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x05R\n" +
	"percentage\"'\n" +
	"\n" +
	"UserIDRule\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIdsB;Z9github.com/rafaelmaier/featureflags/proto/v1;featureflagsb\x06proto3"

var (
	file_proto_v1_common_proto_rawDescOnce sync.Once
	file_proto_v1_common_proto_rawDescData []byte
)

func file_proto_v1_common_proto_rawDescGZIP() []byte {
	file_proto_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_common_proto_rawDesc), len(file_proto_v1_common_proto_rawDesc)))
	})
	return file_proto_v1_common_proto_rawDescData
}

var file_proto_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v1_common_proto_goTypes = []any{
	(*FeatureFlag)(nil),    // 0: featureflags.v1.FeatureFlag
	(*Rule)(nil),           // 1: featureflags.v1.Rule
	(*PercentageRule)(nil), // 2: featureflags.v1.PercentageRule
	(*UserIDRule)(nil),     // 3: featureflags.v1.UserIDRule
}
var file_proto_v1_common_proto_depIdxs = []int32{
	1, // 0: featureflags.v1.FeatureFlag.rules:type_name -> featureflags.v1.Rule
	2, // 1: featureflags.v1.Rule.percentage:type_name -> featureflags.v1.PercentageRule
	3, // 2: featureflags.v1.Rule.user_id:type_name -> featureflags.v1.UserIDRule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_common_proto_init() }
func file_proto_v1_common_proto_init() {
	if File_proto_v1_common_proto != nil {
		return
	}
	file_proto_v1_common_proto_msgTypes[1].OneofWrappers = []any{
		(*Rule_Percentage)(nil),
		(*Rule_UserId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_common_proto_rawDesc), len(file_proto_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_v1_common_proto_depIdxs,
		MessageInfos:      file_proto_v1_common_proto_msgTypes,
	}.Build()
	File_proto_v1_common_proto = out.File
	file_proto_v1_common_proto_goTypes = nil
	file_proto_v1_common_proto_depIdxs = nil
}
