// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/v1/streaming.proto

package featureflags

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeatureStreamingService_Subscribe_FullMethodName = "/featureflags.v1.FeatureStreamingService/Subscribe"
)

// FeatureStreamingServiceClient is the client API for FeatureStreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeatureStreamingServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FeatureUpdate], error)
}

type featureStreamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureStreamingServiceClient(cc grpc.ClientConnInterface) FeatureStreamingServiceClient {
	return &featureStreamingServiceClient{cc}
}

func (c *featureStreamingServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FeatureUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FeatureStreamingService_ServiceDesc.Streams[0], FeatureStreamingService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, FeatureUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeatureStreamingService_SubscribeClient = grpc.ServerStreamingClient[FeatureUpdate]

// FeatureStreamingServiceServer is the server API for FeatureStreamingService service.
// All implementations must embed UnimplementedFeatureStreamingServiceServer
// for forward compatibility.
type FeatureStreamingServiceServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[FeatureUpdate]) error
	mustEmbedUnimplementedFeatureStreamingServiceServer()
}

// UnimplementedFeatureStreamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeatureStreamingServiceServer struct{}

func (UnimplementedFeatureStreamingServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[FeatureUpdate]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedFeatureStreamingServiceServer) mustEmbedUnimplementedFeatureStreamingServiceServer() {
}
func (UnimplementedFeatureStreamingServiceServer) testEmbeddedByValue() {}

// UnsafeFeatureStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureStreamingServiceServer will
// result in compilation errors.
type UnsafeFeatureStreamingServiceServer interface {
	mustEmbedUnimplementedFeatureStreamingServiceServer()
}

func RegisterFeatureStreamingServiceServer(s grpc.ServiceRegistrar, srv FeatureStreamingServiceServer) {
	// If the following call panics, it indicates UnimplementedFeatureStreamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeatureStreamingService_ServiceDesc, srv)
}

func _FeatureStreamingService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeatureStreamingServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, FeatureUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeatureStreamingService_SubscribeServer = grpc.ServerStreamingServer[FeatureUpdate]

// FeatureStreamingService_ServiceDesc is the grpc.ServiceDesc for FeatureStreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureStreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "featureflags.v1.FeatureStreamingService",
	HandlerType: (*FeatureStreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _FeatureStreamingService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/streaming.proto",
}
