// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/v1/streaming.proto

package featureflags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNSPECIFIED UpdateType = 0
	UpdateType_CREATED                 UpdateType = 1
	UpdateType_UPDATED                 UpdateType = 2
	UpdateType_DELETED                 UpdateType = 3
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNSPECIFIED",
		1: "CREATED",
		2: "UPDATED",
		3: "DELETED",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNSPECIFIED": 0,
		"CREATED":                 1,
		"UPDATED":                 2,
		"DELETED":                 3,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_streaming_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_proto_v1_streaming_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{0}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_v1_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type FeatureUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       *FeatureFlag           `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Type          UpdateType             `protobuf:"varint,2,opt,name=type,proto3,enum=featureflags.v1.UpdateType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureUpdate) Reset() {
	*x = FeatureUpdate{}
	mi := &file_proto_v1_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureUpdate) ProtoMessage() {}

func (x *FeatureUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureUpdate.ProtoReflect.Descriptor instead.
func (*FeatureUpdate) Descriptor() ([]byte, []int) {
	return file_proto_v1_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureUpdate) GetFeature() *FeatureFlag {
	if x != nil {
		return x.Feature
	}
	return nil
}

func (x *FeatureUpdate) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_UPDATE_TYPE_UNSPECIFIED
}

var File_proto_v1_streaming_proto protoreflect.FileDescriptor

const file_proto_v1_streaming_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/streaming.proto\x12\x0ffeatureflags.v1\x1a\x15proto/v1/common.proto\"/\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"x\n" +
	"\rFeatureUpdate\x126\n" +
	"\afeature\x18\x01 \x01(\v2\x1c.featureflags.v1.FeatureFlagR\afeature\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.featureflags.v1.UpdateTypeR\x04type*P\n" +
	"\n" +
	"UpdateType\x12\x1b\n" +
	"\x17UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\v\n" +
	"\aUPDATED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x032k\n" +
	"\x17FeatureStreamingService\x12P\n" +
	"\tSubscribe\x12!.featureflags.v1.SubscribeRequest\x1a\x1e.featureflags.v1.FeatureUpdate0\x01B;Z9github.com/rafaelmaier/featureflags/proto/v1;featureflagsb\x06proto3"

var (
	file_proto_v1_streaming_proto_rawDescOnce sync.Once
	file_proto_v1_streaming_proto_rawDescData []byte
)

func file_proto_v1_streaming_proto_rawDescGZIP() []byte {
	file_proto_v1_streaming_proto_rawDescOnce.Do(func() {
		file_proto_v1_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_streaming_proto_rawDesc), len(file_proto_v1_streaming_proto_rawDesc)))
	})
	return file_proto_v1_streaming_proto_rawDescData
}

var file_proto_v1_streaming_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_streaming_proto_goTypes = []any{
	(UpdateType)(0),          // 0: featureflags.v1.UpdateType
	(*SubscribeRequest)(nil), // 1: featureflags.v1.SubscribeRequest
	(*FeatureUpdate)(nil),    // 2: featureflags.v1.FeatureUpdate
	(*FeatureFlag)(nil),      // 3: featureflags.v1.FeatureFlag
}
var file_proto_v1_streaming_proto_depIdxs = []int32{
	3, // 0: featureflags.v1.FeatureUpdate.feature:type_name -> featureflags.v1.FeatureFlag
	0, // 1: featureflags.v1.FeatureUpdate.type:type_name -> featureflags.v1.UpdateType
	1, // 2: featureflags.v1.FeatureStreamingService.Subscribe:input_type -> featureflags.v1.SubscribeRequest
	2, // 3: featureflags.v1.FeatureStreamingService.Subscribe:output_type -> featureflags.v1.FeatureUpdate
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_streaming_proto_init() }
func file_proto_v1_streaming_proto_init() {
	if File_proto_v1_streaming_proto != nil {
		return
	}
	file_proto_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_streaming_proto_rawDesc), len(file_proto_v1_streaming_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_streaming_proto_goTypes,
		DependencyIndexes: file_proto_v1_streaming_proto_depIdxs,
		EnumInfos:         file_proto_v1_streaming_proto_enumTypes,
		MessageInfos:      file_proto_v1_streaming_proto_msgTypes,
	}.Build()
	File_proto_v1_streaming_proto = out.File
	file_proto_v1_streaming_proto_goTypes = nil
	file_proto_v1_streaming_proto_depIdxs = nil
}
